name: main

on: [push]

env:
  azure_CR: adam5283.azurecr.io
  azure_RG: github

jobs:
  build-and-deploy-to-CR:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: adam5283.azurecr.io
        username: ${{ secrets.azure_github_cr_user }}
        password: ${{ secrets.azure_github_cr_pass }}

    - run: |
        docker build . -t ${{env.azure_CR}}/helloworld:latest
        docker push ${{env.azure_CR}}/helloworld:latest
